/* Generated By:JavaCC: Do not edit this line. HtmlTokenizerTreeConstants.java Version 5.0 */
package org.dbdoclet.html.tokenizer.parser;

public interface HtmlTokenizerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTTAG = 1;
  public int JJTCOMMENT = 2;
  public int JJTTEXT = 3;
  public int JJTNCNAME = 4;
  public int JJTEQUALS = 5;
  public int JJTATTRNAME = 6;
  public int JJTATTRVALUE = 7;
  public int JJTSKIPTO = 8;
  public int JJTTOATTRIBUTESASTEXT = 9;
  public int JJTSETPROGRESSLISTENERS = 10;
  public int JJTFIREPROGRESSEVENT = 11;
  public int JJTTRACE = 12;


  public String[] jjtNodeName = {
    "start",
    "tag",
    "comment",
    "text",
    "ncname",
    "equals",
    "attrName",
    "attrValue",
    "skipTo",
    "toAttributesAsText",
    "setProgressListeners",
    "fireProgressEvent",
    "trace",
  };
}
/* JavaCC - OriginalChecksum=e07756ec0e61b98ddbcd44676fb4d021 (do not edit this line) */
