/* Generated By:JJTree: Do not edit this line. NodeRoot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=SampleDataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dbdoclet.xsd.sage;

public
class NodeRoot extends SimpleNode {
  public NodeRoot(int id) {
    super(id);
  }

  public NodeRoot(SampleDataParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SampleDataParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=13f40a2f9bd2032462e116b74e2a33e1 (do not edit this line) */
