/* Generated By:JJTree: Do not edit this line. NodeValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=SampleDataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dbdoclet.xsd.sage;

public
class NodeValue extends SimpleNode {
  public NodeValue(int id) {
    super(id);
  }

  public NodeValue(SampleDataParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SampleDataParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2b4720ece7e2962f6ee75a13a3e84345 (do not edit this line) */
