/* Generated By:JJTree&JavaCC: Do not edit this line. SampleDataParserConstants.java */
package org.dbdoclet.xsd.sage;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SampleDataParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DATA = 5;
  /** RegularExpression Id. */
  int OPTIONS = 6;
  /** RegularExpression Id. */
  int UNIQUE = 7;
  /** RegularExpression Id. */
  int FOLLOWS = 8;
  /** RegularExpression Id. */
  int WORD = 9;
  /** RegularExpression Id. */
  int VALUE = 10;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int VALUES = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"DATA\"",
    "\"OPTIONS\"",
    "\"unique\"",
    "\"follows\"",
    "<WORD>",
    "<VALUE>",
    "\"=\"",
  };

}
