/* Generated By:JavaCC: Do not edit this line. SampleDataParserVisitor.java Version 5.0 */
package org.dbdoclet.xsd.sage;

public interface SampleDataParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(NodeRoot node, Object data);
  public Object visit(NodeOptionName node, Object data);
  public Object visit(NodeOptionValue node, Object data);
  public Object visit(NodeValue node, Object data);
}
/* JavaCC - OriginalChecksum=65acb9726869deafe0b4fc41f8f13f23 (do not edit this line) */
