/* Generated By:JavaCC: Do not edit this line. SampleDataParserTreeConstants.java Version 5.0 */
package org.dbdoclet.xsd.sage;

public interface SampleDataParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTOPTIONNAME = 1;
  public int JJTOPTIONVALUE = 2;
  public int JJTVALUE = 3;


  public String[] jjtNodeName = {
    "Root",
    "OptionName",
    "OptionValue",
    "Value",
  };
}
/* JavaCC - OriginalChecksum=2270b9f3f3426f6ac1d8f92bb55961bd (do not edit this line) */
