/* Generated By:JavaCC: Do not edit this line. CssParserVisitor.java Version 5.0 */
package org.dbdoclet.css.parser.jjt;

public interface CssParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(NodeStart node, Object data);
  public Object visit(NodeSelector node, Object data);
  public Object visit(NodeRuleName node, Object data);
  public Object visit(NodeRuleValue node, Object data);
}
/* JavaCC - OriginalChecksum=50a2bb45003019647ad05660f6ee0ee4 (do not edit this line) */
