/* Generated By:JavaCC: Do not edit this line. CssParserTreeConstants.java Version 5.0 */
package org.dbdoclet.css.parser.jjt;

public interface CssParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSELECTOR = 1;
  public int JJTVOID = 2;
  public int JJTRULENAME = 3;
  public int JJTRULEVALUE = 4;


  public String[] jjtNodeName = {
    "Start",
    "Selector",
    "void",
    "RuleName",
    "RuleValue",
  };
}
/* JavaCC - OriginalChecksum=3e4414a1a10f45b5eab908c9a35fe29b (do not edit this line) */
