/* Generated By:JJTree&JavaCC: Do not edit this line. CssParserConstants.java */
package org.dbdoclet.css.parser.jjt;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CssParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WORD = 5;
  /** RegularExpression Id. */
  int UNIVERSAL_RULE = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int LETTER = 8;
  /** RegularExpression Id. */
  int NAME_START_CHAR = 9;
  /** RegularExpression Id. */
  int NOT_NAME_START_CHAR = 10;
  /** RegularExpression Id. */
  int NAME_CHAR = 11;
  /** RegularExpression Id. */
  int NAME = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<WORD>",
    "\"*\"",
    "<DIGIT>",
    "<LETTER>",
    "<NAME_START_CHAR>",
    "<NOT_NAME_START_CHAR>",
    "<NAME_CHAR>",
    "<NAME>",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\";\"",
  };

}
