/* Generated By:JJTree: Do not edit this line. NodeRuleName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=CssNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dbdoclet.css.parser.jjt;

public
class NodeRuleName extends SimpleNode {
  public NodeRuleName(int id) {
    super(id);
  }

  public NodeRuleName(CssParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CssParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d2264accd4053ff1a2c593f545c6223b (do not edit this line) */
