/* Generated By:JJTree: Do not edit this line. NodeRuleValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=CssNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dbdoclet.css.parser.jjt;

public
class NodeRuleValue extends SimpleNode {
  public NodeRuleValue(int id) {
    super(id);
  }

  public NodeRuleValue(CssParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CssParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=21421e1a2bc92e50bcdcb1c888724fe4 (do not edit this line) */
