/* Generated By:JJTree: Do not edit this line. NodeSelector.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=CssNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dbdoclet.css.parser.jjt;

public
class NodeSelector extends SimpleNode {
  public NodeSelector(int id) {
    super(id);
  }

  public NodeSelector(CssParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CssParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=22142f8304ec179873a0f09d35349d1f (do not edit this line) */
